inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

require:
  - rubocop-rails

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Exclude:
    - components/*/*.gemspec

Gemspec/RequireMFA:
  Exclude:
    - components/*/*.gemspec
