# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Blog::ApplicationMailer`.
# Please instead update this file by running `bin/tapioca dsl Blog::ApplicationMailer`.

class Blog::ApplicationMailer; end
