# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Blog::Author`.
# Please instead update this file by running `bin/tapioca dsl Blog::Author`.

class Blog::Author
  include FrozenRecordAttributeMethods

  module FrozenRecordAttributeMethods
    sig { returns(T.untyped) }
    def name; end

    sig { returns(T::Boolean) }
    def name?; end

    sig { returns(T.untyped) }
    def slug; end

    sig { returns(T::Boolean) }
    def slug?; end
  end
end
