# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Platform::ApplicationMailer`.
# Please instead update this file by running `bin/tapioca dsl Platform::ApplicationMailer`.

class Platform::ApplicationMailer; end
