shared:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("PRIMARY_DATABASE_HOST") { "localhost" } %>
  password: <%= ENV.fetch("PRIMARY_DATABASE_USERNAME") { "postgres" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PRIMARY_DATABASE_PASSWORD") { "postgres" } %>

development:
  primary:
    database: twilling_development

test:
  primary:
    database: twilling_test

production:
  primary:
    database: twilling_production
    username: twilling
    password: <%= ENV["PRIMARY_DATABASE_PASSWORD"] %>
