# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PublicSite::ApplicationMailer`.
# Please instead update this file by running `bin/tapioca dsl PublicSite::ApplicationMailer`.


class PublicSite::ApplicationMailer; end
