name: ✅ RSpec

on: [push]

env:
  RAILS_ENV: test

permissions:
  contents: read

jobs:
  Specs:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        directory: [spec, components]

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - run: bin/rails db:setup

      - name: Run specs
        run: bin/rspec ${{ matrix.directory }}/
